server:
  host: 0.0.0.0
  port: 4000
swagger:
  title: New Web's Technologies course with NestJS
  description: The Website API description
  version: 1.0
  tag: Website
  path: documentation
mongodb:
  uri: mongodb://0.0.0.0:27017/nest
  options:
    useNewUrlParser: true
    useUnifiedTopology: true
    useFindAndModify: false
